export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const ADD_TO_CART = "ADD_TO_CART";
export const FIT_ITEM_QTY = "FIT_ITEM_QTY";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const SHOW_CURRENT_ITEM = "SHOW_CURRENT_ITEM";
